# Name(s)
David Barnett

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

Can this code be executed in the command line?
Can this code be directly converted to raw python code without JSON formatting?
How well does Jupyter's formatting convert to other notebook/markdown formats? (Like R markdown)

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

In [32]:
import numpy as np
import pandas as pd

## Exercise 1

In [33]:
# YOUR SOLUTION HERE
a = np.array([[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2]])
print(a) 

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [34]:
# YOUR SOLUTION HERE
b = np.array([[3,1,1,1],[1,3,1,1],[1,1,3,1],[1,1,1,3],[1,1,1,1],[1,1,1,1]])
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [35]:
# YOUR SOLUTION HERE
print(a*b)
print("a*b works because each number in a is multiplied by the number its corresponding position in b")
print("The dot product will not work, however, because a 6X4 matrix cannot be multiplied by another 6X4 matrix")

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]
a*b works because each number in a is multiplied by the number its corresponding position in b
The dot product will not work, however, because a 6X4 matrix cannot be multiplied by another 6X4 matrix


## Exercise 4

In [36]:
# YOUR SOLUTION HERE
print(np.dot(a.transpose(),b))
print()
print(np.dot(a,b.transpose()))

print("The matrices are different sizes because both have a different number of rows than columns, meaning the first matrix must be 4X4 and the second matrix must be 6X6")

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]

[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]
The matrices are different sizes because both have a different number of rows than columns, meaning the first matrix must be 4X4 and the second matrix must be 6X6


## Exercise 5

In [37]:
# YOUR SOLUTION HERE
def greeting(x):
    if x == True:
        print("Hello")
    else:
        print("Goodbye")
        
greeting(True)
greeting(False)

Hello
Goodbye


## Exercise 6

In [38]:
# YOUR SOLUTION HERE
def array_math():
    arr1 = [1,2,3]
    arr2 = [4,5,6]
    arr3 = [7,8,9]
    print("Mean 1:", np.mean(arr1))
    print("Mean 2:", np.mean(arr2))
    print("Mean 3:", np.mean(arr3))
    print("Sum:", np.sum(arr1) + sum(arr2) + sum(arr3))
    
array_math()

Mean 1: 2.0
Mean 2: 5.0
Mean 3: 8.0
Sum: 45


## Exercise 7

In [39]:
# YOUR SOLUTION HERE
def ones(array):
    sum = 0
    for arr1 in array:
        for arr2 in arr1:
            if arr2 == 1:
                sum += 1
    print(sum)
    
arr = np.array([[1, 5, 8, 4], [0, 1, 2, 1], [9, 9, 5, 3]])
ones(arr)

3


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [40]:
# YOUR SOLUTION HERE
a = pd.DataFrame([[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2]])
print(a)

   0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [41]:
# YOUR SOLUTION HERE
b = pd.DataFrame([[3,1,1,1],[1,3,1,1],[1,1,3,1],[1,1,1,3],[1,1,1,1],[1,1,1,1]])
print(b)

   0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1


## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [42]:
# YOUR SOLUTION HERE
print(a.mul(b))
print("Still no dot product because dot product multiplies by the outer dimensions, which are not the same number")

   0  1  2  3
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2
Still no dot product because dot product multiplies by the outer dimensions, which are not the same number


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [43]:
# YOUR SOLUTION HERE
def ones(dataframe):
    sum = 0
    for i, row in dataframe.iterrows():
        for arr2 in row:
            if arr2 == 1:
                sum += 1
    print(sum)
    
df = pd.DataFrame([[1, 5, 8, 4], [0, 1, 2, 1], [9, 9, 5, 3]])
ones(df)

3


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [44]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [45]:
## YOUR SOLUTION HERE
titanic_df["name"]

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [46]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

female_df = titanic_df.loc[["female"]]

print(female_df.head())
female_df.shape[0]

        pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   

         age  sibsp  parch  ticket      fare    cabin embarked boat  body  \
sex                                                                         
female  29.0      0      0   24160  211.3375       B5        S    2   NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN   NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN   NaN   
female  63.0      1      0   13502   77.9583       D7        S   10   NaN  

466

## Exercise 14
How do you reset the index?

In [47]:
## YOUR SOLUTION HERE
titanic_df.reset_index()

sex  pclass  survived  \
0     female       1         1   
1       male       1         1   
2     female       1         0   
3       male       1         0   
4     female       1         0   
...      ...     ...       ...   
1304  female       3         0   
1305  female       3         0   
1306    male       3         0   
1307    male       3         0   
1308    male       3         0   

                                                 name      age  sibsp  parch  \
0                       Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                      Allison, Master. Hudson Trevor   0.9167      1      2   
2                        Allison, Miss. Helen Loraine   2.0000      1      2   
3                Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                               ...      ...    ...    ...   
1304                             Zabour, Miss. Hileni  14.5000      1      0   
1305                            Zabour, Miss. Thamine      NaN      1      0   
1306                        Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                              Zakarian, Mr. Ortin  27.0000      0      0   
1308                               Zimmerman, Mr. Leo  29.0000      0      0   

      ticket      fare    cabin embarked boat   body  \
0      24160  211.3375       B5        S    2    NaN   
1     113781  151.5500  C22 C26        S   11    NaN   
2     113781  151.5500  C22 C26        S  NaN    NaN   
3     113781  151.5500  C22 C26        S  NaN  135.0   
4     113781  151.5500  C22 C26        S  NaN    NaN   
...      ...       ...      ...      ...  ...    ...   
1304    2665   14.4542      NaN        C  NaN  328.0   
1305    2665   14.4542      NaN        C  NaN    NaN   
1306    2656    7.2250      NaN        C  NaN  304.0   
1307    2670    7.2250      NaN        C  NaN    NaN   
1308  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 14 columns]